### ISSUE TITLE
[Bug Report]: 浏览器自动填充密码时，建议隐藏password

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Blazor#1433]
### Masa.Blazor version

1.0.0

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/93168234/cb7b74fb-b5ac-4307-b220-6d626e7b2377)

https://auth-test.masastack.com/User

**Comment by capdiem** [comment]
@MayueCif 调查了一下，edge需要点击才会将密码和账号填充到输入框，此时会触发input事件。但chrome浏览器会自动添加，不会触发input事件或其他事件，似乎无法让值更新到Blazor的状态。目前有个解决办法是，password输入框type默认为text，此时不会触发自动填充的行为，但用户点击输入框再设置为password。

**Comment by capdiem** [comment]
- Avoid overlapping the label with the input:

  ```razor
  <MTextField @bind-Value="name" Label="Name" @ref="_textField"></MTextField>
  
  @code {
      private MTextField<string>? _textField;
      protected override async Task OnAfterRenderAsync(bool firstRender)
      {
          if (firstRender)
          {
              await JS.InvokeVoidAsync(JsInteropConstants.AddCls, _textField?.LabelReference?.Ref, "m-label--active");
          }
      }
  }
  ```

- Set the background color for autofill:

  ```css
  input:-webkit-autofill {
    box-shadow: 0 0 0 1000px white inset !important;
    -webkit-box-shadow: 0 0 0 1000px #ffffff inset !important;
  }
  ```
