### ISSUE TITLE
'Selectable' and 'Unselectable' row for DataTable is not visually distinguishable enough

### ISSUE THREAD

**Issue by LinQiaoPorco** [masastack/MASA.Blazor#2149]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/4f128f00-10bd-4b86-a5a1-c01e04d23a4d)
 Users can only see the grey color is a little lighter in 'Unselectable' row than normal rows

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/4bdeddf3-769e-44fe-a728-73b651d98f74).
We can have a better comparison between rows Selectable and Unselectable

**Describe alternatives you've considered**

**Additional context**

**Comment by capdiem** [comment]
@LinQiaoPorco Thank you for your feedback! I completely agree with your suggestion and plan to implement it in the upcoming v1.8.0 release.

**Comment by capdiem** [comment]
@LinQiaoPorco After careful consideration, I believe it's best not to change too many default styles. Instead, I have slightly adjusted the disabled color and added a class name `m-data-table__disabled`. If you're not satisfied with the new disabled color, you can customize the row styles based on this new class name. 
```css
.theme--light.m-data-table tr.m-data-table__disabled {
  color: rgba(0, 0, 0, .38);
}

.theme--dark.m-data-table tr.m-data-table__disabled {
  color: rgba(255, 255, 255, .5);
}
```

This will be released in v1.7.3.
